// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.6
// source: proto/consultation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsultationService_RegisterExpert_FullMethodName        = "/consultation.ConsultationService/RegisterExpert"
	ConsultationService_ListAvailableExperts_FullMethodName  = "/consultation.ConsultationService/ListAvailableExperts"
	ConsultationService_CreateBooking_FullMethodName         = "/consultation.ConsultationService/CreateBooking"
	ConsultationService_CancelBooking_FullMethodName         = "/consultation.ConsultationService/CancelBooking"
	ConsultationService_GetUserBookings_FullMethodName       = "/consultation.ConsultationService/GetUserBookings"
	ConsultationService_ConfirmBookingPayment_FullMethodName = "/consultation.ConsultationService/ConfirmBookingPayment"
)

// ConsultationServiceClient is the client API for ConsultationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsultationServiceClient interface {
	RegisterExpert(ctx context.Context, in *ExpertData, opts ...grpc.CallOption) (*ExpertProfile, error)
	ListAvailableExperts(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*ExpertList, error)
	CreateBooking(ctx context.Context, in *BookingData, opts ...grpc.CallOption) (*BookingResponse, error)
	CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*BookingResponse, error)
	GetUserBookings(ctx context.Context, in *GetUserBookingsRequest, opts ...grpc.CallOption) (*BookingList, error)
	ConfirmBookingPayment(ctx context.Context, in *ConfirmPaymentRequest, opts ...grpc.CallOption) (*Empty, error)
}

type consultationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsultationServiceClient(cc grpc.ClientConnInterface) ConsultationServiceClient {
	return &consultationServiceClient{cc}
}

func (c *consultationServiceClient) RegisterExpert(ctx context.Context, in *ExpertData, opts ...grpc.CallOption) (*ExpertProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpertProfile)
	err := c.cc.Invoke(ctx, ConsultationService_RegisterExpert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consultationServiceClient) ListAvailableExperts(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*ExpertList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpertList)
	err := c.cc.Invoke(ctx, ConsultationService_ListAvailableExperts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consultationServiceClient) CreateBooking(ctx context.Context, in *BookingData, opts ...grpc.CallOption) (*BookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, ConsultationService_CreateBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consultationServiceClient) CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*BookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, ConsultationService_CancelBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consultationServiceClient) GetUserBookings(ctx context.Context, in *GetUserBookingsRequest, opts ...grpc.CallOption) (*BookingList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingList)
	err := c.cc.Invoke(ctx, ConsultationService_GetUserBookings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consultationServiceClient) ConfirmBookingPayment(ctx context.Context, in *ConfirmPaymentRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ConsultationService_ConfirmBookingPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsultationServiceServer is the server API for ConsultationService service.
// All implementations must embed UnimplementedConsultationServiceServer
// for forward compatibility.
type ConsultationServiceServer interface {
	RegisterExpert(context.Context, *ExpertData) (*ExpertProfile, error)
	ListAvailableExperts(context.Context, *Filter) (*ExpertList, error)
	CreateBooking(context.Context, *BookingData) (*BookingResponse, error)
	CancelBooking(context.Context, *CancelBookingRequest) (*BookingResponse, error)
	GetUserBookings(context.Context, *GetUserBookingsRequest) (*BookingList, error)
	ConfirmBookingPayment(context.Context, *ConfirmPaymentRequest) (*Empty, error)
	mustEmbedUnimplementedConsultationServiceServer()
}

// UnimplementedConsultationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsultationServiceServer struct{}

func (UnimplementedConsultationServiceServer) RegisterExpert(context.Context, *ExpertData) (*ExpertProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterExpert not implemented")
}
func (UnimplementedConsultationServiceServer) ListAvailableExperts(context.Context, *Filter) (*ExpertList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAvailableExperts not implemented")
}
func (UnimplementedConsultationServiceServer) CreateBooking(context.Context, *BookingData) (*BookingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBooking not implemented")
}
func (UnimplementedConsultationServiceServer) CancelBooking(context.Context, *CancelBookingRequest) (*BookingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelBooking not implemented")
}
func (UnimplementedConsultationServiceServer) GetUserBookings(context.Context, *GetUserBookingsRequest) (*BookingList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserBookings not implemented")
}
func (UnimplementedConsultationServiceServer) ConfirmBookingPayment(context.Context, *ConfirmPaymentRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmBookingPayment not implemented")
}
func (UnimplementedConsultationServiceServer) mustEmbedUnimplementedConsultationServiceServer() {}
func (UnimplementedConsultationServiceServer) testEmbeddedByValue()                             {}

// UnsafeConsultationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsultationServiceServer will
// result in compilation errors.
type UnsafeConsultationServiceServer interface {
	mustEmbedUnimplementedConsultationServiceServer()
}

func RegisterConsultationServiceServer(s grpc.ServiceRegistrar, srv ConsultationServiceServer) {
	// If the following call panics, it indicates UnimplementedConsultationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsultationService_ServiceDesc, srv)
}

func _ConsultationService_RegisterExpert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpertData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsultationServiceServer).RegisterExpert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsultationService_RegisterExpert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsultationServiceServer).RegisterExpert(ctx, req.(*ExpertData))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsultationService_ListAvailableExperts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsultationServiceServer).ListAvailableExperts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsultationService_ListAvailableExperts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsultationServiceServer).ListAvailableExperts(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsultationService_CreateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsultationServiceServer).CreateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsultationService_CreateBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsultationServiceServer).CreateBooking(ctx, req.(*BookingData))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsultationService_CancelBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsultationServiceServer).CancelBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsultationService_CancelBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsultationServiceServer).CancelBooking(ctx, req.(*CancelBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsultationService_GetUserBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBookingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsultationServiceServer).GetUserBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsultationService_GetUserBookings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsultationServiceServer).GetUserBookings(ctx, req.(*GetUserBookingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsultationService_ConfirmBookingPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsultationServiceServer).ConfirmBookingPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsultationService_ConfirmBookingPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsultationServiceServer).ConfirmBookingPayment(ctx, req.(*ConfirmPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsultationService_ServiceDesc is the grpc.ServiceDesc for ConsultationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsultationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consultation.ConsultationService",
	HandlerType: (*ConsultationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterExpert",
			Handler:    _ConsultationService_RegisterExpert_Handler,
		},
		{
			MethodName: "ListAvailableExperts",
			Handler:    _ConsultationService_ListAvailableExperts_Handler,
		},
		{
			MethodName: "CreateBooking",
			Handler:    _ConsultationService_CreateBooking_Handler,
		},
		{
			MethodName: "CancelBooking",
			Handler:    _ConsultationService_CancelBooking_Handler,
		},
		{
			MethodName: "GetUserBookings",
			Handler:    _ConsultationService_GetUserBookings_Handler,
		},
		{
			MethodName: "ConfirmBookingPayment",
			Handler:    _ConsultationService_ConfirmBookingPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/consultation.proto",
}
