// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: proto/consultation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_proto_consultation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_consultation_proto_rawDescGZIP(), []int{0}
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type GetUserBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBookingsRequest) Reset() {
	*x = GetUserBookingsRequest{}
	mi := &file_proto_consultation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBookingsRequest) ProtoMessage() {}

func (x *GetUserBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBookingsRequest.ProtoReflect.Descriptor instead.
func (*GetUserBookingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_consultation_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserBookingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BookingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*BookingDetail       `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingList) Reset() {
	*x = BookingList{}
	mi := &file_proto_consultation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingList) ProtoMessage() {}

func (x *BookingList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingList.ProtoReflect.Descriptor instead.
func (*BookingList) Descriptor() ([]byte, []int) {
	return file_proto_consultation_proto_rawDescGZIP(), []int{2}
}

func (x *BookingList) GetBookings() []*BookingDetail {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type BookingDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpertId      string                 `protobuf:"bytes,3,opt,name=expert_id,json=expertId,proto3" json:"expert_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ScheduledAt   string                 `protobuf:"bytes,5,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	MeetingLink   string                 `protobuf:"bytes,6,opt,name=meeting_link,json=meetingLink,proto3" json:"meeting_link,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpertName    string                 `protobuf:"bytes,8,opt,name=expert_name,json=expertName,proto3" json:"expert_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingDetail) Reset() {
	*x = BookingDetail{}
	mi := &file_proto_consultation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingDetail) ProtoMessage() {}

func (x *BookingDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingDetail.ProtoReflect.Descriptor instead.
func (*BookingDetail) Descriptor() ([]byte, []int) {
	return file_proto_consultation_proto_rawDescGZIP(), []int{3}
}

func (x *BookingDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookingDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookingDetail) GetExpertId() string {
	if x != nil {
		return x.ExpertId
	}
	return ""
}

func (x *BookingDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BookingDetail) GetScheduledAt() string {
	if x != nil {
		return x.ScheduledAt
	}
	return ""
}

func (x *BookingDetail) GetMeetingLink() string {
	if x != nil {
		return x.MeetingLink
	}
	return ""
}

func (x *BookingDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BookingDetail) GetExpertName() string {
	if x != nil {
		return x.ExpertName
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_consultation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_consultation_proto_rawDescGZIP(), []int{4}
}

type ExpertData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Specialization  string                 `protobuf:"bytes,2,opt,name=specialization,proto3" json:"specialization,omitempty"`
	PricePerSession float64                `protobuf:"fixed64,3,opt,name=price_per_session,json=pricePerSession,proto3" json:"price_per_session,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExpertData) Reset() {
	*x = ExpertData{}
	mi := &file_proto_consultation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpertData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpertData) ProtoMessage() {}

func (x *ExpertData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpertData.ProtoReflect.Descriptor instead.
func (*ExpertData) Descriptor() ([]byte, []int) {
	return file_proto_consultation_proto_rawDescGZIP(), []int{5}
}

func (x *ExpertData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExpertData) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *ExpertData) GetPricePerSession() float64 {
	if x != nil {
		return x.PricePerSession
	}
	return 0
}

type ExpertProfile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Specialization  string                 `protobuf:"bytes,3,opt,name=specialization,proto3" json:"specialization,omitempty"`
	PricePerSession float64                `protobuf:"fixed64,4,opt,name=price_per_session,json=pricePerSession,proto3" json:"price_per_session,omitempty"`
	IsAvailable     bool                   `protobuf:"varint,5,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExpertProfile) Reset() {
	*x = ExpertProfile{}
	mi := &file_proto_consultation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpertProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpertProfile) ProtoMessage() {}

func (x *ExpertProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpertProfile.ProtoReflect.Descriptor instead.
func (*ExpertProfile) Descriptor() ([]byte, []int) {
	return file_proto_consultation_proto_rawDescGZIP(), []int{6}
}

func (x *ExpertProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExpertProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExpertProfile) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *ExpertProfile) GetPricePerSession() float64 {
	if x != nil {
		return x.PricePerSession
	}
	return 0
}

func (x *ExpertProfile) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type ExpertList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Experts       []*ExpertProfile       `protobuf:"bytes,1,rep,name=experts,proto3" json:"experts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpertList) Reset() {
	*x = ExpertList{}
	mi := &file_proto_consultation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpertList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpertList) ProtoMessage() {}

func (x *ExpertList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpertList.ProtoReflect.Descriptor instead.
func (*ExpertList) Descriptor() ([]byte, []int) {
	return file_proto_consultation_proto_rawDescGZIP(), []int{7}
}

func (x *ExpertList) GetExperts() []*ExpertProfile {
	if x != nil {
		return x.Experts
	}
	return nil
}

type Filter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Specialization string                 `protobuf:"bytes,1,opt,name=specialization,proto3" json:"specialization,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_consultation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_consultation_proto_rawDescGZIP(), []int{8}
}

func (x *Filter) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

type BookingData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpertId      string                 `protobuf:"bytes,2,opt,name=expert_id,json=expertId,proto3" json:"expert_id,omitempty"`
	ScheduledAt   string                 `protobuf:"bytes,3,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	ExpertName    string                 `protobuf:"bytes,4,opt,name=expert_name,json=expertName,proto3" json:"expert_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingData) Reset() {
	*x = BookingData{}
	mi := &file_proto_consultation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingData) ProtoMessage() {}

func (x *BookingData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingData.ProtoReflect.Descriptor instead.
func (*BookingData) Descriptor() ([]byte, []int) {
	return file_proto_consultation_proto_rawDescGZIP(), []int{9}
}

func (x *BookingData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookingData) GetExpertId() string {
	if x != nil {
		return x.ExpertId
	}
	return ""
}

func (x *BookingData) GetScheduledAt() string {
	if x != nil {
		return x.ScheduledAt
	}
	return ""
}

func (x *BookingData) GetExpertName() string {
	if x != nil {
		return x.ExpertName
	}
	return ""
}

type BookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	MeetingLink   string                 `protobuf:"bytes,3,opt,name=meeting_link,json=meetingLink,proto3" json:"meeting_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingResponse) Reset() {
	*x = BookingResponse{}
	mi := &file_proto_consultation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingResponse) ProtoMessage() {}

func (x *BookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingResponse.ProtoReflect.Descriptor instead.
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_consultation_proto_rawDescGZIP(), []int{10}
}

func (x *BookingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BookingResponse) GetMeetingLink() string {
	if x != nil {
		return x.MeetingLink
	}
	return ""
}

type ConfirmPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentRequest) Reset() {
	*x = ConfirmPaymentRequest{}
	mi := &file_proto_consultation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentRequest) ProtoMessage() {}

func (x *ConfirmPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consultation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_consultation_proto_rawDescGZIP(), []int{11}
}

func (x *ConfirmPaymentRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

var File_proto_consultation_proto protoreflect.FileDescriptor

const file_proto_consultation_proto_rawDesc = "" +
	"\n" +
	"\x18proto/consultation.proto\x12\fconsultation\"5\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"1\n" +
	"\x16GetUserBookingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\vBookingList\x127\n" +
	"\bbookings\x18\x01 \x03(\v2\x1b.consultation.BookingDetailR\bbookings\"\xf3\x01\n" +
	"\rBookingDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\texpert_id\x18\x03 \x01(\tR\bexpertId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\fscheduled_at\x18\x05 \x01(\tR\vscheduledAt\x12!\n" +
	"\fmeeting_link\x18\x06 \x01(\tR\vmeetingLink\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vexpert_name\x18\b \x01(\tR\n" +
	"expertName\"\a\n" +
	"\x05Empty\"y\n" +
	"\n" +
	"ExpertData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0especialization\x18\x02 \x01(\tR\x0especialization\x12*\n" +
	"\x11price_per_session\x18\x03 \x01(\x01R\x0fpricePerSession\"\xaf\x01\n" +
	"\rExpertProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12&\n" +
	"\x0especialization\x18\x03 \x01(\tR\x0especialization\x12*\n" +
	"\x11price_per_session\x18\x04 \x01(\x01R\x0fpricePerSession\x12!\n" +
	"\fis_available\x18\x05 \x01(\bR\visAvailable\"C\n" +
	"\n" +
	"ExpertList\x125\n" +
	"\aexperts\x18\x01 \x03(\v2\x1b.consultation.ExpertProfileR\aexperts\"0\n" +
	"\x06Filter\x12&\n" +
	"\x0especialization\x18\x01 \x01(\tR\x0especialization\"f\n" +
	"\vBookingData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\texpert_id\x18\x02 \x01(\tR\bexpertId\x12!\n" +
	"\fscheduled_at\x18\x03 \x01(\tR\vscheduledAt\"\\\n" +
	"\x0fBookingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fmeeting_link\x18\x03 \x01(\tR\vmeetingLink\"6\n" +
	"\x15ConfirmPaymentRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId2\xec\x03\n" +
	"\x13ConsultationService\x12G\n" +
	"\x0eRegisterExpert\x12\x18.consultation.ExpertData\x1a\x1b.consultation.ExpertProfile\x12F\n" +
	"\x14ListAvailableExperts\x12\x14.consultation.Filter\x1a\x18.consultation.ExpertList\x12I\n" +
	"\rCreateBooking\x12\x19.consultation.BookingData\x1a\x1d.consultation.BookingResponse\x12R\n" +
	"\rCancelBooking\x12\".consultation.CancelBookingRequest\x1a\x1d.consultation.BookingResponse\x12R\n" +
	"\x0fGetUserBookings\x12$.consultation.GetUserBookingsRequest\x1a\x19.consultation.BookingList\x12Q\n" +
	"\x15ConfirmBookingPayment\x12#.consultation.ConfirmPaymentRequest\x1a\x13.consultation.EmptyB?Z=github.com/KaminurOrynbek/BiznesAsh/ConsultationService/protob\x06proto3"

var (
	file_proto_consultation_proto_rawDescOnce sync.Once
	file_proto_consultation_proto_rawDescData []byte
)

func file_proto_consultation_proto_rawDescGZIP() []byte {
	file_proto_consultation_proto_rawDescOnce.Do(func() {
		file_proto_consultation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_consultation_proto_rawDesc), len(file_proto_consultation_proto_rawDesc)))
	})
	return file_proto_consultation_proto_rawDescData
}

var file_proto_consultation_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_consultation_proto_goTypes = []any{
	(*CancelBookingRequest)(nil),   // 0: consultation.CancelBookingRequest
	(*GetUserBookingsRequest)(nil), // 1: consultation.GetUserBookingsRequest
	(*BookingList)(nil),            // 2: consultation.BookingList
	(*BookingDetail)(nil),          // 3: consultation.BookingDetail
	(*Empty)(nil),                  // 4: consultation.Empty
	(*ExpertData)(nil),             // 5: consultation.ExpertData
	(*ExpertProfile)(nil),          // 6: consultation.ExpertProfile
	(*ExpertList)(nil),             // 7: consultation.ExpertList
	(*Filter)(nil),                 // 8: consultation.Filter
	(*BookingData)(nil),            // 9: consultation.BookingData
	(*BookingResponse)(nil),        // 10: consultation.BookingResponse
	(*ConfirmPaymentRequest)(nil),  // 11: consultation.ConfirmPaymentRequest
}
var file_proto_consultation_proto_depIdxs = []int32{
	3,  // 0: consultation.BookingList.bookings:type_name -> consultation.BookingDetail
	6,  // 1: consultation.ExpertList.experts:type_name -> consultation.ExpertProfile
	5,  // 2: consultation.ConsultationService.RegisterExpert:input_type -> consultation.ExpertData
	8,  // 3: consultation.ConsultationService.ListAvailableExperts:input_type -> consultation.Filter
	9,  // 4: consultation.ConsultationService.CreateBooking:input_type -> consultation.BookingData
	0,  // 5: consultation.ConsultationService.CancelBooking:input_type -> consultation.CancelBookingRequest
	1,  // 6: consultation.ConsultationService.GetUserBookings:input_type -> consultation.GetUserBookingsRequest
	11, // 7: consultation.ConsultationService.ConfirmBookingPayment:input_type -> consultation.ConfirmPaymentRequest
	6,  // 8: consultation.ConsultationService.RegisterExpert:output_type -> consultation.ExpertProfile
	7,  // 9: consultation.ConsultationService.ListAvailableExperts:output_type -> consultation.ExpertList
	10, // 10: consultation.ConsultationService.CreateBooking:output_type -> consultation.BookingResponse
	10, // 11: consultation.ConsultationService.CancelBooking:output_type -> consultation.BookingResponse
	2,  // 12: consultation.ConsultationService.GetUserBookings:output_type -> consultation.BookingList
	4,  // 13: consultation.ConsultationService.ConfirmBookingPayment:output_type -> consultation.Empty
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_consultation_proto_init() }
func file_proto_consultation_proto_init() {
	if File_proto_consultation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_consultation_proto_rawDesc), len(file_proto_consultation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_consultation_proto_goTypes,
		DependencyIndexes: file_proto_consultation_proto_depIdxs,
		MessageInfos:      file_proto_consultation_proto_msgTypes,
	}.Build()
	File_proto_consultation_proto = out.File
	file_proto_consultation_proto_goTypes = nil
	file_proto_consultation_proto_depIdxs = nil
}
