// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: notification/notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsRequest) Reset() {
	*x = GetNotificationsRequest{}
	mi := &file_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsRequest) ProtoMessage() {}

func (x *GetNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *GetNotificationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetNotificationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetNotificationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	IsRead        bool                   `protobuf:"varint,5,opt,name=isRead,proto3" json:"isRead,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	PostId        string                 `protobuf:"bytes,7,opt,name=postId,proto3" json:"postId,omitempty"`
	CommentId     string                 `protobuf:"bytes,8,opt,name=commentId,proto3" json:"commentId,omitempty"`
	Data          map[string]string      `protobuf:"bytes,9,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notification) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Notification) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Notification) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *Notification) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsResponse) Reset() {
	*x = GetNotificationsResponse{}
	mi := &file_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsResponse) ProtoMessage() {}

func (x *GetNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *GetNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *GetNotificationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetNotificationsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetNotificationsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type EmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	mi := &file_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *EmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CommentNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=postId,proto3" json:"postId,omitempty"`
	CommentText   string                 `protobuf:"bytes,3,opt,name=commentText,proto3" json:"commentText,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentNotification) Reset() {
	*x = CommentNotification{}
	mi := &file_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentNotification) ProtoMessage() {}

func (x *CommentNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentNotification.ProtoReflect.Descriptor instead.
func (*CommentNotification) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *CommentNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CommentNotification) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CommentNotification) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

func (x *CommentNotification) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ReportNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=postId,proto3" json:"postId,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportNotification) Reset() {
	*x = ReportNotification{}
	mi := &file_notification_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNotification) ProtoMessage() {}

func (x *ReportNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNotification.ProtoReflect.Descriptor instead.
func (*ReportNotification) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ReportNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReportNotification) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *ReportNotification) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type NewPostNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostTitle     string                 `protobuf:"bytes,2,opt,name=postTitle,proto3" json:"postTitle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewPostNotification) Reset() {
	*x = NewPostNotification{}
	mi := &file_notification_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewPostNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPostNotification) ProtoMessage() {}

func (x *NewPostNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPostNotification.ProtoReflect.Descriptor instead.
func (*NewPostNotification) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{6}
}

func (x *NewPostNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NewPostNotification) GetPostTitle() string {
	if x != nil {
		return x.PostTitle
	}
	return ""
}

type PostUpdateNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=postId,proto3" json:"postId,omitempty"`
	UpdateSummary string                 `protobuf:"bytes,3,opt,name=updateSummary,proto3" json:"updateSummary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUpdateNotification) Reset() {
	*x = PostUpdateNotification{}
	mi := &file_notification_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUpdateNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUpdateNotification) ProtoMessage() {}

func (x *PostUpdateNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUpdateNotification.ProtoReflect.Descriptor instead.
func (*PostUpdateNotification) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{7}
}

func (x *PostUpdateNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostUpdateNotification) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostUpdateNotification) GetUpdateSummary() string {
	if x != nil {
		return x.UpdateSummary
	}
	return ""
}

type PostLikeNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostLikeNotification) Reset() {
	*x = PostLikeNotification{}
	mi := &file_notification_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostLikeNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLikeNotification) ProtoMessage() {}

func (x *PostLikeNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLikeNotification.ProtoReflect.Descriptor instead.
func (*PostLikeNotification) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{8}
}

func (x *PostLikeNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostLikeNotification) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type CommentLikeNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CommentId     string                 `protobuf:"bytes,2,opt,name=commentId,proto3" json:"commentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentLikeNotification) Reset() {
	*x = CommentLikeNotification{}
	mi := &file_notification_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentLikeNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentLikeNotification) ProtoMessage() {}

func (x *CommentLikeNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentLikeNotification.ProtoReflect.Descriptor instead.
func (*CommentLikeNotification) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{9}
}

func (x *CommentLikeNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CommentLikeNotification) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type SystemMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMessageRequest) Reset() {
	*x = SystemMessageRequest{}
	mi := &file_notification_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessageRequest) ProtoMessage() {}

func (x *SystemMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessageRequest.ProtoReflect.Descriptor instead.
func (*SystemMessageRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{10}
}

func (x *SystemMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SystemMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_notification_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{11}
}

func (x *UserID) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_notification_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{12}
}

func (x *NotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []string               `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionsResponse) Reset() {
	*x = SubscriptionsResponse{}
	mi := &file_notification_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionsResponse) ProtoMessage() {}

func (x *SubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{13}
}

func (x *SubscriptionsResponse) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

var File_notification_notification_proto protoreflect.FileDescriptor

const file_notification_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fnotification/notification.proto\x12\fnotification\"[\n" +
	"\x17GetNotificationsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xc3\x02\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06isRead\x18\x05 \x01(\bR\x06isRead\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06postId\x18\a \x01(\tR\x06postId\x12\x1c\n" +
	"\tcommentId\x18\b \x01(\tR\tcommentId\x128\n" +
	"\x04data\x18\t \x03(\v2$.notification.Notification.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\x18GetNotificationsResponse\x12@\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1a.notification.NotificationR\rnotifications\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"R\n" +
	"\fEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"\x85\x01\n" +
	"\x13CommentNotification\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06postId\x18\x02 \x01(\tR\x06postId\x12 \n" +
	"\vcommentText\x18\x03 \x01(\tR\vcommentText\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"\\\n" +
	"\x12ReportNotification\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06postId\x18\x02 \x01(\tR\x06postId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"K\n" +
	"\x13NewPostNotification\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tpostTitle\x18\x02 \x01(\tR\tpostTitle\"n\n" +
	"\x16PostUpdateNotification\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06postId\x18\x02 \x01(\tR\x06postId\x12$\n" +
	"\rupdateSummary\x18\x03 \x01(\tR\rupdateSummary\"F\n" +
	"\x14PostLikeNotification\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06postId\x18\x02 \x01(\tR\x06postId\"O\n" +
	"\x17CommentLikeNotification\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tcommentId\x18\x02 \x01(\tR\tcommentId\"H\n" +
	"\x14SystemMessageRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\x06UserID\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"J\n" +
	"\x14NotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x15SubscriptionsResponse\x12$\n" +
	"\rsubscriptions\x18\x01 \x03(\tR\rsubscriptions2\xa9\t\n" +
	"\x13NotificationService\x12R\n" +
	"\x10SendWelcomeEmail\x12\x1a.notification.EmailRequest\x1a\".notification.NotificationResponse\x12`\n" +
	"\x17SendCommentNotification\x12!.notification.CommentNotification\x1a\".notification.NotificationResponse\x12^\n" +
	"\x16SendReportNotification\x12 .notification.ReportNotification\x1a\".notification.NotificationResponse\x12V\n" +
	"\rNotifyNewPost\x12!.notification.NewPostNotification\x1a\".notification.NotificationResponse\x12\\\n" +
	"\x10NotifyPostUpdate\x12$.notification.PostUpdateNotification\x1a\".notification.NotificationResponse\x12W\n" +
	"\x15SendVerificationEmail\x12\x1a.notification.EmailRequest\x1a\".notification.NotificationResponse\x12]\n" +
	"\x13NotifySystemMessage\x12\".notification.SystemMessageRequest\x1a\".notification.NotificationResponse\x12N\n" +
	"\x12SubscribeToUpdates\x12\x14.notification.UserID\x1a\".notification.NotificationResponse\x12R\n" +
	"\x16UnsubscribeFromUpdates\x12\x14.notification.UserID\x1a\".notification.NotificationResponse\x12M\n" +
	"\x10GetSubscriptions\x12\x14.notification.UserID\x1a#.notification.SubscriptionsResponse\x12X\n" +
	"\x0eNotifyPostLike\x12\".notification.PostLikeNotification\x1a\".notification.NotificationResponse\x12^\n" +
	"\x11NotifyCommentLike\x12%.notification.CommentLikeNotification\x1a\".notification.NotificationResponse\x12a\n" +
	"\x10GetNotifications\x12%.notification.GetNotificationsRequest\x1a&.notification.GetNotificationsResponseBGZEgithub.com/KaminurOrynbek/BiznesAsh_lib/proto/auto-proto/notificationb\x06proto3"

var (
	file_notification_notification_proto_rawDescOnce sync.Once
	file_notification_notification_proto_rawDescData []byte
)

func file_notification_notification_proto_rawDescGZIP() []byte {
	file_notification_notification_proto_rawDescOnce.Do(func() {
		file_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)))
	})
	return file_notification_notification_proto_rawDescData
}

var file_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_notification_notification_proto_goTypes = []any{
	(*GetNotificationsRequest)(nil),  // 0: notification.GetNotificationsRequest
	(*Notification)(nil),             // 1: notification.Notification
	(*GetNotificationsResponse)(nil), // 2: notification.GetNotificationsResponse
	(*EmailRequest)(nil),             // 3: notification.EmailRequest
	(*CommentNotification)(nil),      // 4: notification.CommentNotification
	(*ReportNotification)(nil),       // 5: notification.ReportNotification
	(*NewPostNotification)(nil),      // 6: notification.NewPostNotification
	(*PostUpdateNotification)(nil),   // 7: notification.PostUpdateNotification
	(*PostLikeNotification)(nil),     // 8: notification.PostLikeNotification
	(*CommentLikeNotification)(nil),  // 9: notification.CommentLikeNotification
	(*SystemMessageRequest)(nil),     // 10: notification.SystemMessageRequest
	(*UserID)(nil),                   // 11: notification.UserID
	(*NotificationResponse)(nil),     // 12: notification.NotificationResponse
	(*SubscriptionsResponse)(nil),    // 13: notification.SubscriptionsResponse
	nil,                              // 14: notification.Notification.DataEntry
}
var file_notification_notification_proto_depIdxs = []int32{
	14, // 0: notification.Notification.data:type_name -> notification.Notification.DataEntry
	1,  // 1: notification.GetNotificationsResponse.notifications:type_name -> notification.Notification
	3,  // 2: notification.NotificationService.SendWelcomeEmail:input_type -> notification.EmailRequest
	4,  // 3: notification.NotificationService.SendCommentNotification:input_type -> notification.CommentNotification
	5,  // 4: notification.NotificationService.SendReportNotification:input_type -> notification.ReportNotification
	6,  // 5: notification.NotificationService.NotifyNewPost:input_type -> notification.NewPostNotification
	7,  // 6: notification.NotificationService.NotifyPostUpdate:input_type -> notification.PostUpdateNotification
	3,  // 7: notification.NotificationService.SendVerificationEmail:input_type -> notification.EmailRequest
	10, // 8: notification.NotificationService.NotifySystemMessage:input_type -> notification.SystemMessageRequest
	11, // 9: notification.NotificationService.SubscribeToUpdates:input_type -> notification.UserID
	11, // 10: notification.NotificationService.UnsubscribeFromUpdates:input_type -> notification.UserID
	11, // 11: notification.NotificationService.GetSubscriptions:input_type -> notification.UserID
	8,  // 12: notification.NotificationService.NotifyPostLike:input_type -> notification.PostLikeNotification
	9,  // 13: notification.NotificationService.NotifyCommentLike:input_type -> notification.CommentLikeNotification
	0,  // 14: notification.NotificationService.GetNotifications:input_type -> notification.GetNotificationsRequest
	12, // 15: notification.NotificationService.SendWelcomeEmail:output_type -> notification.NotificationResponse
	12, // 16: notification.NotificationService.SendCommentNotification:output_type -> notification.NotificationResponse
	12, // 17: notification.NotificationService.SendReportNotification:output_type -> notification.NotificationResponse
	12, // 18: notification.NotificationService.NotifyNewPost:output_type -> notification.NotificationResponse
	12, // 19: notification.NotificationService.NotifyPostUpdate:output_type -> notification.NotificationResponse
	12, // 20: notification.NotificationService.SendVerificationEmail:output_type -> notification.NotificationResponse
	12, // 21: notification.NotificationService.NotifySystemMessage:output_type -> notification.NotificationResponse
	12, // 22: notification.NotificationService.SubscribeToUpdates:output_type -> notification.NotificationResponse
	12, // 23: notification.NotificationService.UnsubscribeFromUpdates:output_type -> notification.NotificationResponse
	13, // 24: notification.NotificationService.GetSubscriptions:output_type -> notification.SubscriptionsResponse
	12, // 25: notification.NotificationService.NotifyPostLike:output_type -> notification.NotificationResponse
	12, // 26: notification.NotificationService.NotifyCommentLike:output_type -> notification.NotificationResponse
	2,  // 27: notification.NotificationService.GetNotifications:output_type -> notification.GetNotificationsResponse
	15, // [15:28] is the sub-list for method output_type
	2,  // [2:15] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_notification_notification_proto_init() }
func file_notification_notification_proto_init() {
	if File_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_notification_proto_goTypes,
		DependencyIndexes: file_notification_notification_proto_depIdxs,
		MessageInfos:      file_notification_notification_proto_msgTypes,
	}.Build()
	File_notification_notification_proto = out.File
	file_notification_notification_proto_goTypes = nil
	file_notification_notification_proto_depIdxs = nil
}
